### ISSUE TITLE
deployment error

### ISSUE THREAD

**Issue by noble-ch** [Susmita-Dey/Netflix-Clone#4]
both the live demo links  ([netflix-clone-susmita-dey.vercel.app/](https://netflix-clone-susmita-dey.vercel.app/)   and  https://susmita-dey.github.io/Netflix-Clone/  doesn't redirect to the proper page or lead to broken page

**Comment by Raj2342** [comment]
hey i  resolved deployement  error -  here is a link - https://stellar-syrniki-ba5e05.netlify.app/
